// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dokpueifqrmvsiyshimn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRva3B1ZWlmcXJtdnNpeXNoaW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjY1MjYsImV4cCI6MjA3MDY0MjUyNn0.sMCg86VUZqiqwgk7HANRb9BeMOILyNxdJVgWdOC43LQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});